### ISSUE TITLE
meme

### ISSUE THREAD

**Issue by Zanexsas** [taticalSniper/zanequinha-station-br#2]
![3e7f030a34c8b55faea7a82ac26cee02](https://user-images.githubusercontent.com/24799276/53304360-10fd7d80-3853-11e9-8a08-b8f92c9f1194.png)
oh admin 
![dgv2awe57n921](https://user-images.githubusercontent.com/24799276/53304363-7d787c80-3853-11e9-9ef3-31901fb74e0a.jpg)

**Comment by davipatury** [comment]
:joy: :joy: :joy: :joy: :ok_hand: :ok_hand: :ok_hand: :ok_hand:

**Comment by taticalSniper** [comment]
estou
avergiuando
![sam braba s que nao e braba ok](https://user-images.githubusercontent.com/23741603/53304388-676abc00-3853-11e9-8104-b4914123cb5f.jpg)

**Comment by davipatury** [comment]
como fecha

**Comment by davipatury** [comment]
:scream: :scream: :scream: :scream: :scream_cat:  :scream:  :scream:
